# Generated by Django 3.2.8 on 2021-11-07 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 10, 48, 59, 181508)),
        ),
    ]
