# Generated by Django 3.2.8 on 2021-11-10 16:22

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211107_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 16, 22, 48, 760961)),
        ),
        migrations.AlterField(
            model_name='page',
            name='img_url',
            field=models.URLField(validators=[app.models.img_validator]),
        ),
    ]
