# Generated by Django 3.2.8 on 2021-11-10 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211110_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 16, 25, 20, 690565)),
        ),
    ]
