# Generated by Django 4.0 on 2021-12-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_date'),
        ('app', '0011_alter_comment_date'),
    ]

    operations = [
    ]
